development: &default
  adapter: postgresql
  encoding: unicode
  database: ideas
  pool: 5



test:
  adapter: postgresql
  encoding: unicode
  database: ideas
  pool: 5

# production:
#   <<: *default
#   database: db/production.sqlite3
